export const ErrorCode = {
  DUPLICATE_ACTIVE_PAYMENT: 'DUPLICATE_ACTIVE_PAYMENT',
  INCOMPLETE_PAYMENT_EXISTS: 'INCOMPLETE_PAYMENT_EXISTS',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  NO_PLATFORM_ADDRESS: 'NO_PLATFORM_ADDRESS',
  STATE_MISMATCH: 'STATE_MISMATCH',
  CHAIN_ERROR: 'CHAIN_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
} as const;
